# This file consists of two parts:
# 1. The first part defines the Persistent Volume.
# 2. The second part of the file defines the Persistent Volume Claim

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:                         # This section contains the specifications for the PV.
  storageClassName: manual    # Storage class to be used for this PV.
  capacity:                   
    storage: 10Gi             # Sets the capacity of the PV to 10gigabytes.
  accessModes:               
    - ReadWriteOnce           # Access mode allows the volume to be mounted as read-write by a single node at a time.
  hostPath:                  
    path: "/mnt/data"         # The PV is created using storage located on the host machine at the path “/mnt/data.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi          # Should be equal or less than the PV capacity created.