apiVersion: v1              
kind: Secret                 
metadata:                  
  name: mysql-secret         
type: kubernetes.io/basic-auth 
stringData:                  
  password: dev@123   # There must be a more secure way to create/store this root password!